apiVersion: batch/v1
kind: Job
metadata:
  name: bank-leumi
spec:
  template:
    # This is the pod template
    spec:
      containers:
      - name: bank-leumi
        image: busybox
        command: ['sh', '-c', 'echo "Hello Bank Leumi " && sleep 3600']
      restartPolicy: OnFailure
